package com.alert.app.frontend.status;

public enum StatisticsStatus {

    AIR_QUALITY_STATIONS_UPDATED,
    AIR_QUALITY_SENSORS_UPDATED,
    AIR_QUALITY_INDEXES_UPDATED,
    WEATHER_STATION_UPDATED,
    SUBSCRIBE_E_MAIL_SENT,
    SUBSCRIBE_CREATED,
    LOGIN_SUCCESS,
    LOGOUT_SUCCESS,
    LOGIN_FAILURE,
    USER_CREATED,
    USER_UPDATED
}
